/**
 * scripts/tools/applyProFigures.ts
 *
 * Applique (de façon idempotente) les figures haute-fidélité produites par
 * ProFigureEngine / ProFigureTemplates dans les fichiers de leçons cibles, puis
 * valide chaque figure :
 *   1. substitution du bloc SVG :
 *      - figures sur-mesure : marqueur de commentaire historique ;
 *      - figures à données (proFigureSpecs.ts) : index de bloc (slot) + contrôle
 *        du titre d'ancre — robuste à l'absence/duplication de commentaires ;
 *   2. injection de la règle CSS .pfe-figure (ratio préservé dans l'iframe) ;
 *   3. contrôle jsdom : structure conservée, ids uniques, références url(#..) résolues,
 *      ratio ≥ 1.2, aucun élément hors du panneau de fond.
 *
 * Exécution : npx tsx scripts/tools/applyProFigures.ts [--check]
 *   --check = valide sans écrire (utile en CI / avant commit).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { JSDOM } from 'jsdom';
import { ProFigureEngine } from './ProFigureEngine.ts';
import { PFE_TARGETS, type FigureTarget } from './proFigureSpecs.ts';

const MARKER = '<!-- Generated by ProFigureEngine - SVT BAC DZ -->';
const CSS_RULE = '.doc-visual svg.pfe-figure';

/**
 * Figures « sur-mesure » historiques (gabarits maison de ProFigureEngine) :
 * substitution par marqueur de commentaire HTML — voir `proFigureSpecs.ts`
 * pour les figures à données (ciblage slot + ancre de titre).
 */
interface BespokeTarget {
  /** Chemin de la leçon, relatif à la racine du projet. */
  file: string;
  /** Générateur ProFigureEngine à appliquer. */
  build: () => string;
  /** Marqueurs historiques du SVG primitif à remplacer (si encore présents). */
  legacyMarkers: RegExp[];
}

const BESPOKE_TARGETS: BespokeTarget[] = [
  {
    file: 'public/lessons/phase1_chapitres_1_2.html',
    build: () => ProFigureEngine.generatePancreaticAcidityPulse3Min(),
    legacyMarkers: [/<!--\s*SVG Cell Diagram\s*-->[\s\S]*?<\/svg>/],
  },
  {
    file: 'public/lessons/phase2_chapitres_3_4.html',
    build: () => ProFigureEngine.generatePolysomeTranslation(),
    legacyMarkers: [/<!--\s*SVG Polysome\s*-->[\s\S]*?<\/svg>/],
  },
];

/** Remplace la figure sur-mesure (marqueur ProFigureEngine) ou le SVG primitif. */
function injectBespoke(html: string, svg: string, legacyMarkers: RegExp[]): string {
  const generated = new RegExp(`${MARKER}[\\s\\S]*?<\\/svg>`);
  if (generated.test(html)) return html.replace(generated, () => svg);

  for (const marker of legacyMarkers) {
    if (marker.test(html)) return html.replace(marker, () => svg);
  }
  throw new Error('aucun emplacement de figure trouvé (ni bloc généré, ni SVG primitif)');
}

/** Titre <h1..h4> le plus proche situé AVANT `index` (balises retirées, espaces réduits). */
function headingBefore(html: string, index: number): string {
  const headings = [...html.slice(0, index).matchAll(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/g)];
  const last = headings[headings.length - 1];
  if (!last) return '';
  return last[1].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
}

/** Position + titre du i-ème bloc <svg>…</svg> de la leçon (toutes figures confondues). */
function findSlot(html: string, slot: number): { start: number; end: number; heading: string } | null {
  const re = /<svg\b[\s\S]*?<\/svg>/g;
  let index = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html))) {
    if (index === slot) return { start: m.index, end: re.lastIndex, heading: headingBefore(html, m.index) };
    index += 1;
  }
  return null;
}

/**
 * Remplace le bloc indexé `slot` APRÈS vérification du titre d'ancre : si le
 * titre ne correspond plus, on échoue explicitement plutôt que d'écraser la
 * mauvaise figure. Remplacement du dernier slot au premier (offsets valides).
 */
function injectBySlot(html: string, targets: FigureTarget[]): string {
  let out = html;
  /** Insensible aux espaces : évite les faux négatifs (titres à balises/espaces multiples). */
  const norm = (s: string) => s.replace(/\s+/g, '');
  const sorted = [...targets].sort((a, b) => b.slot - a.slot);
  for (const target of sorted) {
    const hit = findSlot(out, target.slot);
    if (!hit) throw new Error(`slot #${target.slot} introuvable (bloc <svg> manquant)`);
    if (!norm(hit.heading).includes(norm(target.anchor))) {
      throw new Error(`ancre « ${target.anchor} » introuvable — titre réel : « ${hit.heading || '(aucun)' } »`);
    }
    // Un marqueur `<!-- Generated by ProFigureEngine -->` peut précéder le <svg> :
    // on l'absorbe sinon la réapplication dupliquerait le marqueur (compteur ×2).
    const marker = /<!--\s*Generated by ProFigureEngine[^>]*-->\s*$/.exec(out.slice(0, hit.start));
    const start = marker ? hit.start - marker[0].length : hit.start;
    out = out.slice(0, start) + target.build() + out.slice(hit.end);
  }
  return out;
}

/** Garantit la règle CSS qui empêche max-height:260px d'écraser le ratio. */
function injectCssRule(html: string): { html: string; changed: boolean } {
  if (html.includes(CSS_RULE)) return { html, changed: false };

  const anchor = /\.svg-container\s*\{[^}]*\}/;
  if (!anchor.test(html)) throw new Error('règle CSS .svg-container introuvable');

  const rule =
    `\n\n        /* ProFigureEngine — préserve le ratio des figures générées ` +
    `(max-height:260px les écrasait) */\n        ${CSS_RULE} {\n            max-height: none;\n        }`;
  return { html: html.replace(anchor, (m) => m + rule), changed: true };
}

/**
 * Préfixe TOUS les ids d'une figure — et ses références internes (url(#…),
 * href="#…", xlink:href="#…") — avec un jeton déterministe propre au couple
 * (leçon, figure).
 *
 * Pourquoi (régression réelle) : chaque figure générée embarque sa copie du bloc
 * `<defs>` partagé des gabarits (pfe-arrow, pfe-membrane-grad, pfe-glow-red…).
 * Deux figures dans le MÊME document (leçons mono-chapitre : lecon_transcription,
 * lecon_representation, lecon_activite_structure) dupliquaient donc ces ids — et
 * dans un document HTML `url(#pfe-arrow)` est résolu vers la PREMIÈRE définition
 * (dégradé/marqueur d'une autre figure). L'invariant « ids uniques »
 * (src/data/lessonRenderParcours.test.ts) le refusait à juste titre.
 *
 * Le jeton est déterministe (slot ou index) : réappliquer le script produit
 * exactement le même document (idempotence préservée).
 */
function namespaceFigureIds(svg: string, token: string): string {
  const map = new Map<string, string>();
  let out = svg.replace(/\bid="([^"]+)"/g, (_m, id: string) => {
    map.set(id, `${token}-${id}`);
    return `id="${token}-${id}"`;
  });
  if (map.size === 0) return out;
  const toId = (id: string) => map.get(id) ?? id;
  out = out.replace(/url\(#([A-Za-z0-9_:.\-]+)\)/g, (m, id: string) => (map.has(id) ? `url(#${toId(id)})` : m));
  out = out.replace(/\b(xlink:href|href)="#([^"]+)"/g, (m, attr: string, id: string) =>
    map.has(id) ? `${attr}="#${toId(id)}"` : m,
  );
  return out;
}

/** Ids apparaissant plus d'une fois dans un document (invariant du viewer). */
function duplicatedIds(html: string): string[] {
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1]);
  return [...new Set(ids.filter((id, i) => ids.indexOf(id) !== i))];
}

/** Ouvre une figure isolée dans jsdom et vérifie intégrité + références internes. */
function verifyFigure(svg: string, label: string): string[] {
  const problems: string[] = [];
  const dom = new JSDOM(`<!DOCTYPE html><body>${svg}</body>`);
  const root = dom.window.document.querySelector('svg');
  if (!root) return [`${label}: jsdom n'a pas pu reconstruire le SVG`];

  // 1. Aucun élément « avalé » par l'analyseur : déclarés == conservés (racine <svg> exclue).
  const declared = (svg.match(/<([a-zA-Z][a-zA-Z0-9]*)[\s/>]/g) || []).length;
  const parsed = root.querySelectorAll('*').length;
  if (declared - 1 !== parsed) {
    problems.push(
      `${label}: structure modifiée à l'analyse (${declared - 1} éléments ` +
        `déclarés, ${parsed} conservés)`,
    );
  }

  // 2. ids uniques dans la figure (sinon les filtres/marqueurs se court-circuitent).
  const ids = Array.from(root.querySelectorAll('[id]')).map((el) => el.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) problems.push(`${label}: ids dupliqués → ${[...new Set(dupes)].join(', ')}`);

  // 3. Toute référence url(#id) doit résoudre dans la figure elle-même.
  const refs = new Set(
    Array.from(root.querySelectorAll('*'))
      .flatMap((el) => Array.from(el.attributes).map((a) => a.value))
      .filter((v) => v.includes('url(#'))
      .map((v) => /url\(#([^)]+)\)/.exec(v)?.[1])
      .filter((v): v is string => Boolean(v)),
  );
  const missing = [...refs].filter((id) => !root.querySelector('#' + id));
  if (missing.length) problems.push(`${label}: références non résolues → ${missing.join(', ')}`);

  // 4. Ratio compatible avec la largeur de la colonne « document » du viewer.
  const [, , w, h] = (root.getAttribute('viewBox') || '').split(/\s+/).map(Number);
  if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) {
    problems.push(`${label}: viewBox invalide`);
  } else if (w / h < 1.2) {
    problems.push(`${label}: ratio ${w}/${h} trop haut pour la colonne`);
  }

  return problems;
}

/** Estime la largeur d'un texte SVG (arabe + latin) sans moteur de mise en page. */
function estimateTextWidth(text: string, fontSize: number): number {
  return text.trim().length * fontSize * 0.5;
}

/** Résout la taille de police : attribut font-size, sinon classe pfe-*, sinon 12. */
function fontSizeOf(el: Element): number {
  const attr = Number(el.getAttribute('font-size'));
  if (Number.isFinite(attr) && attr > 0) return attr;
  const cls = el.getAttribute('class') || '';
  if (cls.includes('pfe-title')) return 15;
  if (cls.includes('pfe-label')) return 13;
  if (cls.includes('pfe-sub')) return 11;
  return 12;
}

/** Cumule les translate() des ancêtres (un seul niveau de <g transform> est utilisé). */
function offsetOf(el: Element, root: Element): { dx: number; dy: number } {
  let dx = 0;
  let dy = 0;
  let node: Element | null = el;
  while (node && node !== root) {
    const t = /translate\(\s*(-?[\d.]+)[\s,]+(-?[\d.]+)\s*\)/.exec(node.getAttribute('transform') || '');
    if (t) {
      dx += Number(t[1]);
      dy += Number(t[2]);
    }
    node = node.parentElement;
  }
  return { dx, dy };
}

/**
 * Vérifie qu'aucun élément ne déborde du panneau de fond de la figure :
 * c'est ce qui provoquait les « schémas coupés / illisibles » signalés.
 */
function verifyGeometry(svg: string, label: string): string[] {
  const problems: string[] = [];
  const dom = new JSDOM(`<!DOCTYPE html><body>${svg}</body>`);
  const root = dom.window.document.querySelector('svg');
  if (!root) return [`${label}: géométrie invérifiable`];

  const [, , vbW, vbH] = (root.getAttribute('viewBox') || '').split(/\s+/).map(Number);
  const rects = Array.from(root.querySelectorAll('rect')).map((r) => ({
    el: r,
    w: Number(r.getAttribute('width')),
    h: Number(r.getAttribute('height')),
  }));
  const panel = rects.find((r) => r.w > vbW * 0.75 && r.h > vbH * 0.75);
  if (!panel) return [`${label}: panneau de fond introuvable (garde-fou géométrique inactif)`];

  const px = Number(panel.el.getAttribute('x'));
  const py = Number(panel.el.getAttribute('y'));
  const TOL = 2;
  const out = (id: string, box: { x1: number; y1: number; x2: number; y2: number }) => {
    if (box.x1 < px - TOL || box.y1 < py - TOL || box.x2 > px + panel.w + TOL || box.y2 > py + panel.h + TOL) {
      problems.push(
        `${label}: ${id} hors panneau [${Math.round(box.x1)},${Math.round(box.y1)} → ` +
          `${Math.round(box.x2)},${Math.round(box.y2)}]`,
      );
    }
  };
  const idOf = (el: Element, i: number) => el.getAttribute('id') || `${el.tagName}#${i}`;

  Array.from(root.querySelectorAll('rect')).forEach((el, i) => {
    if (el === panel.el) return;
    const x = Number(el.getAttribute('x'));
    const y = Number(el.getAttribute('y'));
    const w = Number(el.getAttribute('width'));
    const h = Number(el.getAttribute('height'));
    if (!Number.isFinite(x) || !Number.isFinite(y)) return;
    if (w <= 0 || h <= 0) {
      problems.push(`${label}: ${idOf(el, i)} dimension nulle ou négative (${w}×${h})`);
      return;
    }
    const { dx, dy } = offsetOf(el, root);
    out(idOf(el, i), {
      x1: x + dx,
      y1: y + dy,
      x2: x + dx + w,
      y2: y + dy + h,
    });
  });

  Array.from(root.querySelectorAll('circle, ellipse')).forEach((el, i) => {
    const cx = Number(el.getAttribute('cx'));
    const cy = Number(el.getAttribute('cy'));
    if (!Number.isFinite(cx) || !Number.isFinite(cy)) return;
    const rx = Number(el.getAttribute('rx') ?? el.getAttribute('r'));
    const ry = Number(el.getAttribute('ry') ?? el.getAttribute('r'));
    const { dx, dy } = offsetOf(el, root);
    out(idOf(el, i), { x1: cx - rx + dx, y1: cy - ry + dy, x2: cx + rx + dx, y2: cy + ry + dy });
  });

  Array.from(root.querySelectorAll('text')).forEach((el, i) => {
    const x = Number(el.getAttribute('x'));
    const y = Number(el.getAttribute('y'));
    if (!Number.isFinite(x) || !Number.isFinite(y)) return;
    const size = fontSizeOf(el);
    const w = estimateTextWidth(el.textContent || '', size);
    const anchor = el.getAttribute('text-anchor');
    const x1 = anchor === 'middle' ? x - w / 2 : anchor === 'end' ? x - w : x;
    const { dx, dy } = offsetOf(el, root);
    out(idOf(el, i), { x1: x1 + dx, y1: y - size * 0.8 + dy, x2: x1 + w + dx, y2: y + size * 0.25 + dy });
  });

  return problems;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const problems: string[] = [];
  let failures = 0;

  // Regroupement des cibles par leçon (les SVG comptés sont stables : 1 pour 1).
  const plans = new Map<string, { bespoke: BespokeTarget[]; registry: FigureTarget[] }>();
  const planOf = (file: string) => {
    const plan = plans.get(file) ?? { bespoke: [], registry: [] };
    plans.set(file, plan);
    return plan;
  };
  for (const target of BESPOKE_TARGETS) planOf(target.file).bespoke.push(target);
  for (const target of PFE_TARGETS) planOf(target.file).registry.push(target);

  for (const [file, plan] of plans) {
    const path = resolve(process.cwd(), file);
    const original = readFileSync(path, 'utf8');

    try {
      if (plan.bespoke.length && plan.registry.length) {
        throw new Error('stratégies mixtes (marqueur + slot) non supportées dans une même leçon');
      }

      let next = original;
      const svgs: string[] = [];
      // Chaque figure reçoit des ids préfixés (jeton déterministe) : aucun id
      // dupliqué quand plusieurs figures cohabitent dans le même document.
      for (let i = 0; i < plan.bespoke.length; i += 1) {
        const target = plan.bespoke[i];
        const svg = namespaceFigureIds(target.build(), `pf-b${i}`);
        svgs.push(svg);
        next = injectBespoke(next, svg, target.legacyMarkers);
      }
      if (plan.registry.length) {
        const scoped = plan.registry.map((target) => ({
          ...target,
          build: () => namespaceFigureIds(target.build(), `pf-f${target.slot}`),
        }));
        next = injectBySlot(next, scoped);
        for (const target of scoped) svgs.push(target.build());
      }
      next = injectCssRule(next).html;

      const dupIds = duplicatedIds(next);
      if (dupIds.length) {
        problems.push(`${file}: ids dupliqués dans le document → ${dupIds.slice(0, 6).join(', ')}`);
      }

      for (const svg of svgs) {
        problems.push(...verifyFigure(svg, file));
        problems.push(...verifyGeometry(svg, file));
      }

      if (next !== original && !checkOnly) writeFileSync(path, next, 'utf8');
      const figureCount = (next.match(/Generated by ProFigureEngine/g) || []).length;
      const expected = plan.bespoke.length + plan.registry.length;
      if (figureCount !== expected) {
        problems.push(`${file}: ${figureCount} blocs générés (attendu ${expected})`);
      }

      const state = next === original ? 'inchangé' : checkOnly ? 'à écrire' : 'mis à jour';
      console.log(`✓ ${file} — ${state} · ${expected} figure(s)`);
    } catch (err) {
      failures += 1;
      console.error(`✗ ${file} — ${(err as Error).message}`);
    }
  }

  if (problems.length) {
    console.error(`\n⚠ ${problems.length} problème(s) de fidélité :`);
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
  if (failures) process.exit(1);
  const total = BESPOKE_TARGETS.length + PFE_TARGETS.length;
  console.log(`\n✓ ${plans.size} leçons · ${total} figures ProFigureEngine appliquées et validées`);
}

main();
