/**
 * scripts/tools/ProFigureEngine.ts
 *
 * Moteur de templates SVG scientifiques et publication-grade pour SVT BAC Algérie.
 * Générateur automatisé de schémas biologiques et géologiques vectoriels avec :
 * - Charte chromatique scientifique contrastée et accessible
 * - Typographie bilingue arabe RTL avec termes techniques LTR (ARNm, REG, etc.)
 * - Légendes numérotées, flèches enzymatiques et cinétiques, gradients membranaires
 * - Modèles vectoriels haut de gamme : cellule sécrétrice, cinétique Pulse-Chase, polysome
 */

export interface FigureConfig {
  width?: number;
  height?: number;
  viewBox?: string;
  titleAr?: string;
  subtitleAr?: string;
  theme?: 'dark' | 'light' | 'scientific-blue';
}

export class ProFigureEngine {
  /**
   * Crée un conteneur SVG standardisé avec filtres, dégradés et styles nécessaires.
   */
  public static createSvgHeader(
    config: FigureConfig,
    defsContent: string = ''
  ): { header: string; footer: string } {
    const viewBox = config.viewBox || `0 0 ${config.width || 800} ${config.height || 500}`;
    const header = `<!-- Generated by ProFigureEngine - SVT BAC DZ -->
<svg class="svg-container pfe-figure" viewBox="${viewBox}" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${config.titleAr || 'Scientific Diagram'}">
  <defs>
    <style>
      .pfe-title { font-family: 'Cairo', 'Segoe UI', Tahoma, sans-serif; font-weight: 700; fill: #f8fafc; }
      .pfe-label { font-family: 'Cairo', 'Segoe UI', Tahoma, sans-serif; font-size: 13px; fill: #cbd5e1; }
      .pfe-sub { font-family: 'Segoe UI', Tahoma, sans-serif; font-size: 11px; fill: #94a3b8; }
      .pfe-badge { font-family: monospace; font-size: 11px; font-weight: bold; }
    </style>
    <filter id="pfe-glow-red" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="3" result="blur" />
      <feComposite in="SourceGraphic" in2="blur" operator="over" />
    </filter>
    <marker id="pfe-arrow" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1 L 10 5 L 0 9 z" fill="#38bdf8" />
    </marker>
    <marker id="pfe-arrow-gold" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 1 L 10 5 L 0 9 z" fill="#fbbf24" />
    </marker>
    <linearGradient id="pfe-membrane-grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#1e293b" />
      <stop offset="100%" stop-color="#0f172a" />
    </linearGradient>
    <linearGradient id="pfe-nucleus-grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#1e3a5f" />
      <stop offset="100%" stop-color="#0f172a" />
    </linearGradient>
    ${defsContent}
  </defs>`;

    const footer = `</svg>`;
    return { header, footer };
  }

  /**
   * Template 1 : Cellule acineuse du pancréas (Pulse 3 min).
   */
  public static generatePancreaticAcidityPulse3Min(): string {
    const { header, footer } = this.createSvgHeader({
      viewBox: '0 0 800 480',
      titleAr: 'خلية عنقودية للبنكرياس بعد 3 دقائق من الحضن في وسط به لوسين مشع',
    });

    const body = `
  <rect x="10" y="10" width="780" height="460" rx="24" fill="#0c1322" stroke="#1e293b" stroke-width="2"/>
  <path d="M 50,180 C 50,70 140,40 380,40 C 620,40 750,70 750,200 C 750,340 680,440 420,440 C 180,440 50,360 50,180 Z" fill="url(#pfe-membrane-grad)" stroke="#38bdf8" stroke-width="3"/>
  <text x="30" y="32" class="pfe-sub" fill="#64748b" font-weight="bold">القطب القاعدي (Pôle basal)</text>
  <text x="745" y="452" text-anchor="end" class="pfe-sub" fill="#64748b" font-weight="bold">القطب القمي الإفرازي (Pôle apical)</text>

  <!-- النواة -->
  <g id="nucleus-group">
    <ellipse cx="170" cy="240" rx="90" ry="110" fill="url(#pfe-nucleus-grad)" stroke="#60a5fa" stroke-width="2.5" stroke-dasharray="12 4"/>
    <path d="M 120,220 Q 150,190 190,210 Q 220,240 160,270 Q 130,250 170,220" fill="none" stroke="#3b82f6" stroke-width="2" opacity="0.4"/>
    <circle cx="160" cy="235" r="22" fill="#1d4ed8" opacity="0.5"/>
    <text x="170" y="240" text-anchor="middle" class="pfe-label" font-weight="bold" fill="#bfdbfe">النواة</text>
    <text x="170" y="258" text-anchor="middle" class="pfe-sub">Noyau</text>
  </g>

  <!-- الشبكة الهيولية المحببة REG -->
  <g id="reg-group">
    <path d="M 275,130 C 310,140 330,170 305,210 C 285,240 305,270 325,300 C 340,320 320,350 280,365" fill="none" stroke="#0284c7" stroke-width="9" stroke-linecap="round"/>
    <path d="M 295,120 C 335,135 355,165 330,210 C 310,245 330,275 350,305 C 365,325 345,355 305,375" fill="none" stroke="#38bdf8" stroke-width="8" stroke-linecap="round"/>
    <path d="M 315,110 C 360,130 380,165 355,210 C 335,250 355,280 375,310 C 390,330 370,365 330,385" fill="none" stroke="#7dd3fc" stroke-width="7" stroke-linecap="round"/>

    <!-- الإشعاع المتركز -->
    <g id="radiation-hotspots-reg" filter="url(#pfe-glow-red)">
      <circle cx="295" cy="140" r="6" fill="#ef4444"/><circle cx="312" cy="170" r="6.5" fill="#ef4444"/>
      <circle cx="300" cy="205" r="6" fill="#ef4444"/><circle cx="320" cy="240" r="7" fill="#ef4444"/>
      <circle cx="310" cy="275" r="6" fill="#ef4444"/><circle cx="335" cy="210" r="6.5" fill="#ef4444"/>
      <circle cx="345" cy="270" r="6.5" fill="#ef4444"/><circle cx="330" cy="310" r="6" fill="#ef4444"/>
    </g>
    <g fill="#ffffff">
      <circle cx="295" cy="140" r="2.5"/><circle cx="312" cy="170" r="2.5"/>
      <circle cx="300" cy="205" r="2.5"/><circle cx="320" cy="240" r="3"/>
      <circle cx="310" cy="275" r="2.5"/><circle cx="335" cy="210" r="2.5"/>
    </g>
  </g>

  <!-- جهاز غولجي والحويصلات -->
  <g id="golgi-group">
    <path d="M 460,160 C 485,190 485,240 460,280" fill="none" stroke="#c084fc" stroke-width="6.5" stroke-linecap="round"/>
    <path d="M 480,165 C 505,195 505,235 480,275" fill="none" stroke="#a855f7" stroke-width="6" stroke-linecap="round"/>
    <circle cx="410" cy="180" r="8" fill="#334155" stroke="#a855f7" stroke-width="1.5"/>
    <circle cx="420" cy="230" r="9" fill="#334155" stroke="#a855f7" stroke-width="1.5"/>
  </g>
  <g id="secretory-vesicles-group">
    <circle cx="580" cy="180" r="16" fill="#1e293b" stroke="#64748b" stroke-width="2"/>
    <circle cx="610" cy="240" r="19" fill="#1e293b" stroke="#64748b" stroke-width="2"/>
    <circle cx="590" cy="300" r="17" fill="#1e293b" stroke="#64748b" stroke-width="2"/>
  </g>

  <!-- تسميات ومؤشرات -->
  <path d="M 320,88 L 320,108" stroke="#38bdf8" stroke-width="1.5" marker-end="url(#pfe-arrow)"/>
  <rect x="225" y="56" width="190" height="30" rx="6" fill="#032b44" stroke="#0284c7" stroke-width="1"/>
  <text x="320" y="76" text-anchor="middle" class="pfe-label" font-weight="bold" fill="#7dd3fc">الشبكة الهيولية المحببة (REG)</text>

  <path d="M 485,100 L 485,150" stroke="#c084fc" stroke-width="1.5" marker-end="url(#pfe-arrow)"/>
  <rect x="420" y="70" width="130" height="30" rx="6" fill="#2e1065" stroke="#a855f7" stroke-width="1"/>
  <text x="485" y="90" text-anchor="middle" class="pfe-label" font-weight="bold" fill="#e9d5ff">جهاز غولجي</text>

  <path d="M 580,127 L 580,162" stroke="#94a3b8" stroke-width="1.5" marker-end="url(#pfe-arrow)"/>
  <rect x="545" y="95" width="135" height="30" rx="6" fill="#1e293b" stroke="#64748b" stroke-width="1"/>
  <text x="612" y="115" text-anchor="middle" class="pfe-label" font-weight="bold" fill="#cbd5e1">حويصلات إفرازية</text>

  <rect x="380" y="350" width="260" height="50" rx="10" fill="#1e1b4b" stroke="#6366f1" stroke-width="1.5"/>
  <circle cx="400" cy="375" r="10" fill="#ef4444" filter="url(#pfe-glow-red)"/>
  <circle cx="400" cy="375" r="4" fill="#ffffff"/>
  <text x="420" y="370" font-size="12" font-weight="bold" fill="#e0e7ff">الحالة عند t = 3 دقائق :</text>
  <text x="420" y="390" font-size="11" fill="#a5b4fc">100% من الإشعاع متمركز في الشبكة (REG)</text>
`;

    return `${header}\n${body}\n${footer}`;
  }

  /**
   * Template 2 : Expérience Pulse-Chase (³H-Uracile).
   */
  public static generatePulseChaseUracileTracking(): string {
    const { header, footer } = this.createSvgHeader({
      viewBox: '0 0 840 450',
      titleAr: 'تتبع مسار اليوراسيل المشع عبر تقنية التصوير الإشعاعي الذاتي',
    });

    const body = `
  <rect x="10" y="10" width="820" height="430" rx="24" fill="#0c1322" stroke="#1e293b" stroke-width="2"/>

  <!-- CELLULE 1 : t = 15 min -->
  <g id="cell-t15">
    <rect x="30" y="30" width="360" height="380" rx="18" fill="#111c30" stroke="#1e3a8a" stroke-width="2"/>
    <rect x="50" y="45" width="320" height="38" rx="8" fill="#1e293b" stroke="#3b82f6" stroke-width="1.5"/>
    <text x="210" y="70" text-anchor="middle" class="pfe-title" font-size="15" fill="#60a5fa">⏱️ بعد 15 دقيقة (حضن في ³H-Uracile)</text>

    <ellipse cx="210" cy="245" rx="145" ry="125" fill="#0f172a" stroke="#38bdf8" stroke-width="2.5"/>
    <text x="210" y="145" text-anchor="middle" class="pfe-sub" fill="#64748b">الهيولى (خالية من الإشعاع)</text>

    <circle cx="210" cy="255" r="70" fill="#1e293b" stroke="#60a5fa" stroke-width="3" stroke-dasharray="10 4"/>
    <text x="210" y="225" text-anchor="middle" class="pfe-label" font-weight="bold" fill="#93c5fd">النواة</text>

    <g filter="url(#pfe-glow-red)">
      <circle cx="180" cy="265" r="6" fill="#ef4444"/><circle cx="210" cy="285" r="6.5" fill="#ef4444"/>
      <circle cx="235" cy="260" r="6" fill="#ef4444"/><circle cx="195" cy="245" r="6" fill="#ef4444"/>
      <circle cx="225" cy="240" r="5.5" fill="#ef4444"/><circle cx="245" cy="280" r="6" fill="#ef4444"/>
    </g>
    <g fill="#ffffff">
      <circle cx="180" cy="265" r="2"/><circle cx="210" cy="285" r="2.5"/><circle cx="235" cy="260" r="2"/>
      <circle cx="195" cy="245" r="2"/><circle cx="225" cy="240" r="2"/>
    </g>

    <rect x="60" y="372" width="300" height="34" rx="6" fill="#1e1b4b" stroke="#ef4444" stroke-width="1"/>
    <text x="210" y="394" text-anchor="middle" font-size="12" font-weight="bold" fill="#fca5a5">النتيجة: الإشعاع متمركز كلياً داخل النواة</text>
  </g>

  <!-- Flèche transition -->
  <g id="transition-arrow">
    <path d="M 400,240 L 440,240" stroke="#f59e0b" stroke-width="4" marker-end="url(#pfe-arrow-gold)"/>
    <text x="420" y="214" text-anchor="middle" font-size="10" font-weight="bold" fill="#fbbf24">نقل إلى وسط</text>
    <text x="420" y="229" text-anchor="middle" font-size="10" fill="#fde68a">غير مشع (Chasse)</text>
  </g>

  <!-- CELLULE 2 : t = 90 min -->
  <g id="cell-t90">
    <rect x="450" y="30" width="360" height="380" rx="18" fill="#111c30" stroke="#1e3a8a" stroke-width="2"/>
    <rect x="470" y="45" width="320" height="38" rx="8" fill="#1e293b" stroke="#10b981" stroke-width="1.5"/>
    <text x="630" y="70" text-anchor="middle" class="pfe-title" font-size="15" fill="#34d399">⏱️ بعد 90 دقيقة (في وسط غير مشع)</text>

    <ellipse cx="630" cy="245" rx="145" ry="125" fill="#0f172a" stroke="#10b981" stroke-width="2.5"/>
    <text x="630" y="145" text-anchor="middle" class="pfe-sub" fill="#34d399">الهيولى (مقر تراكم الإشعاع)</text>

    <circle cx="630" cy="255" r="70" fill="#1e293b" stroke="#60a5fa" stroke-width="2.5" stroke-dasharray="10 4"/>
    <text x="630" y="250" text-anchor="middle" class="pfe-label" fill="#64748b">النواة</text>
    <text x="630" y="270" text-anchor="middle" class="pfe-sub" fill="#475569">(شبه منعدم)</text>

    <g filter="url(#pfe-glow-red)">
      <circle cx="530" cy="180" r="6" fill="#ef4444"/><circle cx="730" cy="190" r="6.5" fill="#ef4444"/>
      <circle cx="520" cy="280" r="6" fill="#ef4444"/><circle cx="740" cy="275" r="6.5" fill="#ef4444"/>
      <circle cx="560" cy="330" r="6" fill="#ef4444"/><circle cx="700" cy="335" r="6" fill="#ef4444"/>
      <circle cx="630" cy="350" r="6" fill="#ef4444"/>
    </g>
    <g fill="#ffffff">
      <circle cx="530" cy="180" r="2"/><circle cx="730" cy="190" r="2"/><circle cx="520" cy="280" r="2"/>
      <circle cx="740" cy="275" r="2.5"/><circle cx="560" cy="330" r="2"/><circle cx="700" cy="335" r="2"/>
    </g>

    <path d="M 590,215 Q 560,200 545,190" stroke="#f43f5e" stroke-width="2" stroke-dasharray="3 3"/>
    <path d="M 670,215 Q 700,205 715,198" stroke="#f43f5e" stroke-width="2" stroke-dasharray="3 3"/>

    <rect x="480" y="372" width="300" height="34" rx="6" fill="#064e3b" stroke="#10b981" stroke-width="1"/>
    <text x="630" y="394" text-anchor="middle" font-size="12" font-weight="bold" fill="#6ee7b7">النتيجة: هجرة ARNm من النواة إلى الهيولى</text>
  </g>
`;

    return `${header}\n${body}\n${footer}`;
  }

  /**
   * Template 3 : Polysome (متعدد الريبوزوم).
   */
  public static generatePolysomeTranslation(): string {
    const { header, footer } = this.createSvgHeader({
      viewBox: '0 0 840 450',
      titleAr: 'متعدد الريبوزوم (Polysome) وآلية الرفع من مردود تركيب البروتين',
    });

    const body = `
  <rect x="10" y="10" width="820" height="430" rx="24" fill="#0b1326" stroke="#1e293b" stroke-width="2"/>

  <!-- ARNm Backbone -->
  <g id="mrna-backbone">
    <path d="M 60,240 C 200,230 400,250 780,240" stroke="#f43f5e" stroke-width="6" stroke-linecap="round"/>
    <path d="M 60,240 C 200,230 400,250 780,240" stroke="#fda4af" stroke-width="2" stroke-linecap="round"/>

    <rect x="40" y="215" width="48" height="26" rx="6" fill="#881337" stroke="#f43f5e" stroke-width="1.5"/>
    <text x="64" y="233" text-anchor="middle" font-family="monospace" font-size="14" font-weight="bold" fill="#fecdd3">5'</text>

    <rect x="750" y="215" width="48" height="26" rx="6" fill="#881337" stroke="#f43f5e" stroke-width="1.5"/>
    <text x="774" y="233" text-anchor="middle" font-family="monospace" font-size="14" font-weight="bold" fill="#fecdd3">3'</text>
  </g>

  <!-- Ribosomes -->
  <g id="ribosome-1" transform="translate(150, 240)">
    <ellipse cx="0" cy="18" rx="28" ry="16" fill="#0f766e" stroke="#2dd4bf" stroke-width="2"/>
    <text x="0" y="22" text-anchor="middle" font-size="10" fill="#ccfbf1">40S</text>
    <ellipse cx="0" cy="-18" rx="36" ry="24" fill="#115e59" stroke="#2dd4bf" stroke-width="2.5"/>
    <text x="0" y="-14" text-anchor="middle" font-size="11" font-weight="bold" fill="#ccfbf1">60S</text>
    <path d="M 0,-38 Q -10,-55 -5,-65" fill="none" stroke="#fbbf24" stroke-width="4.5" stroke-linecap="round"/>
    <circle cx="-5" cy="-65" r="5" fill="#f59e0b"/>
  </g>

  <g id="ribosome-2" transform="translate(310, 242)">
    <ellipse cx="0" cy="18" rx="28" ry="16" fill="#0f766e" stroke="#2dd4bf" stroke-width="2"/>
    <ellipse cx="0" cy="-18" rx="36" ry="24" fill="#115e59" stroke="#2dd4bf" stroke-width="2.5"/>
    <text x="0" y="-14" text-anchor="middle" font-size="11" font-weight="bold" fill="#ccfbf1">60S</text>
    <path d="M 0,-38 Q -15,-60 5,-80 Q 20,-100 0,-115" fill="none" stroke="#fbbf24" stroke-width="4.5" stroke-linecap="round"/>
    <circle cx="0" cy="-115" r="6" fill="#f59e0b"/>
  </g>

  <g id="ribosome-3" transform="translate(480, 243)">
    <ellipse cx="0" cy="18" rx="28" ry="16" fill="#0f766e" stroke="#2dd4bf" stroke-width="2"/>
    <ellipse cx="0" cy="-18" rx="36" ry="24" fill="#115e59" stroke="#2dd4bf" stroke-width="2.5"/>
    <text x="0" y="-14" text-anchor="middle" font-size="11" font-weight="bold" fill="#ccfbf1">60S</text>
    <path d="M 0,-38 Q -20,-65 10,-95 Q 30,-125 -10,-145 Q -25,-160 -10,-175" fill="none" stroke="#fbbf24" stroke-width="5" stroke-linecap="round"/>
    <circle cx="-10" cy="-175" r="7" fill="#f59e0b"/>
  </g>

  <g id="ribosome-4" transform="translate(660, 240)">
    <ellipse cx="0" cy="18" rx="28" ry="16" fill="#0f766e" stroke="#2dd4bf" stroke-width="2"/>
    <ellipse cx="0" cy="-18" rx="36" ry="24" fill="#115e59" stroke="#2dd4bf" stroke-width="2.5"/>
    <text x="0" y="-14" text-anchor="middle" font-size="11" font-weight="bold" fill="#ccfbf1">60S</text>
    <path d="M 0,-38 Q -25,-70 15,-105 Q 40,-140 -15,-165 Q -30,-185 10,-205" fill="none" stroke="#fbbf24" stroke-width="5" stroke-linecap="round"/>
    <circle cx="10" cy="-205" r="8" fill="#f59e0b"/>
  </g>

  <!-- Direction de déplacement -->
  <g id="translation-direction">
    <path d="M 140,320 L 680,320" stroke="#38bdf8" stroke-width="3" marker-end="url(#pfe-arrow)"/>
    <rect x="290" y="300" width="260" height="38" rx="8" fill="#0c4a6e" stroke="#38bdf8" stroke-width="1"/>
    <text x="420" y="324" text-anchor="middle" class="pfe-title" font-size="13" fill="#e0f2fe">اتجاه حركة وانتقال الريبوزومات ➡️</text>
    <text x="420" y="355" text-anchor="middle" font-size="11.5" fill="#94a3b8">قراءة الشفرة الوراثية دوماً من النهاية 5' نحو النهاية 3'</text>
  </g>

  <!-- Cartouche pédagogique -->
  <rect x="40" y="30" width="400" height="90" rx="10" fill="#1e1b4b" stroke="#6366f1" stroke-width="1.5"/>
  <text x="55" y="55" font-size="13" font-weight="bold" fill="#a5b4fc">💡 المبدأ العلمي لمتعدد الريبوزوم (Polysome) :</text>
  <text x="55" y="78" font-size="12" fill="#e0e7ff">• كل ريبوزوم يركب سلسلة بيبتيدية متطابقة لنفس البروتين.</text>
  <text x="55" y="100" font-size="12" fill="#fde047">• طول السلسلة يزداد كلما اقترب الريبوزوم من النهاية 3'.</text>
`;

    return `${header}\n${body}\n${footer}`;
  }
}
